### ISSUE TITLE
Include non-admin users

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/HistoryLog#10]
Currently the History Log report generator allows you to filter by users with Admin or Super User roles. Can we also include users with Contributor and Researcher roles to that list?

**Comment by NedHenry** [comment]
Thanks! This problem is now fixed as of version 1.1.6. All users with super user, administrator, contributor, or researcher roles should now be listed when filtering log entries by user. Let me know if you see this problem again.
