### ISSUE TITLE
Upgrade doesn't check ItemHistoryLog table name

### ISSUE THREAD

**Issue by patrickmj** [UCSCLibrary/HistoryLog#15]
A much older version creates a table `item_history_log`. New, current version happily generalizes it to `history_log_entry`, but the upgrade hook doesn't rename the table for a migration that's that old.

**Comment by Daniel-KM** [comment]
Hi,

This is fixed in https://github.com/UCSCLibrary/HistoryLog/pull/16.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
